wam_powerbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  wam/base_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/base_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wam/shoulder_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wam/shoulder_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wam/elbow_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/elbow_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wam/wrist_yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/wrist_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wam/wrist_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/wrist_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wam/palm_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/palm_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wam/bhand/finger_1/prox_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_1/prox_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
  wam/bhand/finger_1/med_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_1/med_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
  wam/bhand/finger_1/dist_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_1/dist_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
  wam/bhand/finger_2/prox_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_2/prox_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
  wam/bhand/finger_2/med_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_2/med_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
  wam/bhand/finger_2/dist_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_2/dist_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
  wam/bhand/finger_3/med_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_3/med_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
  wam/bhand/finger_3/dist_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wam/bhand/finger_3/dist_joint
    pid: {p: 5.0, i: 0.01, d: 2.0}
